{% set name = "daemontools-encore" %}
{% set version = "1.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://untroubled.org/daemontools-encore/{{ name }}-{{ version }}.tar.gz
  sha256: 9f48f3c6cdd3f2b0202532e87f9ff46ea86777ca31ebda3a96bed618104bbd31
  patches:
    - ldflags.patch
    - cflags.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - test -f ${PREFIX}/bin/multilog

about:
  home: https://untroubled.org/daemontools-encore
  license: MIT
  summary: "Collection of tools for managing UNIX services"
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
